### ISSUE TITLE
Getting Failed to connect to host error in ProfileBrowserIDE

### ISSUE THREAD

**Issue by sumeetchhetri** [OSEHRA/docker-vista#18]
After setting up PIP and the ProfileBrowserIDE I get this error while trying to navigate through the IDE application. Also I get these errors in logs,

```
MTM error count: 6
SCA ERROR:      Reason Code: -19
ERROR:  Message: SCAMTM NOTIFICATION:   No active servers.
ERROR:  File: /home/osehra/YDBPIP-master/mtm_V2.4.5/mtmcomm.c Line: 1072
ERROR:  Timestamp: Mon Oct 15 13:37:47 2018
```

While trying to manually invoke pip mtm servers using dm, I get the following errors,
```
root@oshera:/home/osehra/pip# ./dm

OSEHRA>do JOB^PBSUTL("SCA\$IBS",2)
%YDB-E-SETECODE, Non-empty value assigned to $ECODE (user-defined error trap)
                At M source location vRCgetRecord0Opt+7^RecordCTBLSVTYP

OSEHRA>
```

**Comment by ChristopherEdwards** [comment]
remove the escaping for the "$" from the command and it should work: `d JOB^PBSUTL("SCA$IBS",2)`

**Comment by sumeetchhetri** [comment]
Tried this already, it doesn't work, it does not give any errors, but I am still getting similar errors in ProfileBrowser. Ideally the following steps should work correctly,
source /home/osehra/etc/env
/home/osehra/bin/start.sh
This sequence starts the 4 default mumps processes and the mtm server, but I keep getting the first error mentioned above in the logs.

**Comment by sumeetchhetri** [comment]
I though that this was an issue with the kind of manual setup that I had done on an Ubuntu VM following the steps mentioned in the repo. Today I went ahead with the docker steps,
```
docker build --build-arg flags="-b -d -e -m -i osehra -q -s -w -y" -t osehra .
docker run -d -p 8001:8001 -p 9100:9100 -p 9101:9101 -p 61012:61012 -p 9430:9430 -p 2222:22 -p 8080:8080 -p 8081:8081 -p 9080:9080 -p 57772:57772 --name=osehra osehra
```
With this tomcat does not start by default, I then bash the container and then manually start tomcat, but i still see the same errors in mtm logs
```
MTM error count: 6
SCA ERROR:      Reason Code: -19
ERROR:  Message: SCAMTM NOTIFICATION:   No active servers.
ERROR:  File: /home/osehra/YDBPIP-master/mtm_V2.4.5/mtmcomm.c Line: 1072
ERROR:  Timestamp: Mon Oct 15 13:37:47 2018
```
Doing a ./dm and then d ^SCAER results in this dump
```
--------------------------------------------------------------------------------
Device info:

0 OPEN RMS STREAM NOWRAP
0-out OPEN RMS STREAM NOWRAP


--------------------------------------------------------------------------------
Intrinsic info:

$DEVICE=""
$ECODE=""
$ESTACK=5
$ETRAP=""
$HOROLOG="64937,35973"
$IO=0
$JOB=171
$KEY=""
$PRINCIPAL=0
$QUIT=0
$REFERENCE="^CTBL(""SVTYP"",""SCA$IBS"")"
$STACK=5
$STORAGE=2147483647
$SYSTEM="47,gtm_sysid"
$TEST=0
$TLEVEL=0
$TRESTART=0
$X=0
$Y=0
$ZA=0
$ZALLOCSTOR=1089465
$ZB=""
$ZCHSET="M"
$ZCLOSE=0
$ZCMDLINE=""
$ZCOMPILE=""
$ZCSTATUS=0
$ZDATEFORM=0
$ZDIRECTORY="/home/osehra/pip/"
$ZEDITOR=0
$ZEOF=0
$ZERROR="Unprocessed $ZERROR, see $ZSTATUS"
$ZGBLDIR="/home/osehra/g/osehra.gld"
$ZHOROLOG="64937,35973,690522,0"
$ZININTERRUPT=0
$ZINTERRUPT="I $$JOBEXAM^ZU($ZPOSITION)"
$ZIO=0
$ZJOB=0
$ZKEY=""
$ZLEVEL=6
$ZMAXTPTIME=45
$ZMODE="OTHER"
$ZONLNRLBK=0
$ZPATNUMERIC="M"
$ZPIN="0< /"
$ZPOSITION="GetInfo+4^UTLERR"
$ZPOUT="0> /"
$ZPROCESS=""
$ZPROMPT="OSEHRA>"
$ZQUIT=1
$ZREALSTOR=1130337
$ZRELDATE="20180516 12:21"
$ZROUTINES="/home/osehra/p/r1.22_x86_64(/home/osehra/p) /home/osehra/s/r1.22_x86_64(/home/osehra/s) /home/osehra/r/r1.22_x86_64(/home/osehra/r) /home/osehra/pip/prtns /home/osehra/pip/zrtns /home/osehra/pip/srtns/obj(/home/osehra/pip/srtns) /home/osehra/pip/mrtns/obj(/home/osehra/pip/mrtns) /home/osehra/pip/crtns/custom /home/osehra/pip/crtns/profile /home/osehra/pip/crtns/framework /home/osehra/p
ip/crtns/obj(/home/osehra/pip/crtns) /home/osehra/pip/util/obj(/home/osehra/pip/util) /home/osehra/lib/gtm/libgtmutil.so"
$ZSOURCE=""
$ZSTATUS=""
$ZSTEP="B"
$ZSTRPLLIM=0
$ZSYSTEM=0
$ZTNAME=""
$ZTDATA=0
$ZTDELIM=""
$ZTEXIT=""
$ZTLEVEL=0
$ZTOLDVAL=""
$ZTRAP="G NEWJOBER^%ZJOB"
$ZTRIGGEROP=""
$ZTSLATE=""
$ZTUPDATE=""
$ZTVALUE=""
$ZTWORMHOLE=""
$ZUSEDSTOR=1100761
$ZUT=1539683973690566
$ZVERSION="GT.M V6.3-004 Linux x86_64"
$ZYERROR=""
$ZYRELEASE="YottaDB r1.22 Linux x86_64"


--------------------------------------------------------------------------------
Stack info:

GetInfo+7^UTLERR
DSPMAIN+6^UTLERR
UTLERR+6^UTLERR
ERRLOG+23^PBSUTL
SVCNCT+54^PBSSRV


--------------------------------------------------------------------------------
Variable info:

%ZTDY=-1
%zjobref="SVCNCT^PBSSRV(""SCA$IBS"",1)"
ET="%SYSTEM-E-ENO22, Invalid argument"
rms=0
svtyp="Profile Server||0|SVCNCT^PBSSRV||1|1|45||1|MTM|"
vop1=1
vzactive=1
vzcsid=0
vzermsg="%SYSTEM-E-ENO22, Invalid argument"
vzlogmsg=1
vzlogrep=1
vzmaxtim=45
vzmsgpgm=""
vzmtname="MTM"
vzrole="PRIMARY"
vzsttim=""
vzsvfap=""
vzsvfape=""
vzsvid=1
vzsvsec=0
vzsvtyp="SCA$IBS"
vztimout=15
vztrap=1
```

**Comment by ChristopherEdwards** [comment]
What is your run command you may have some sysctl issues within the container.

**Comment by sumeetchhetri** [comment]
docker run -d -p 8001:8001 -p 9100:9100 -p 9101:9101 -p 61012:61012 -p 9430:9430 -p 2222:22 -p 8080:8080 -p 8081:8081 -p 9080:9080 -p 57772:57772 --name=osehra osehra

**Comment by ChristopherEdwards** [comment]
As mentioned here: https://github.com/OSEHRA/docker-vista#installing-sql-mapping

You need some extra flags when running the SQL Mapping:

```
--sysctl kernel.msgmax=1048700 --sysctl kernel.msgmnb=65536000
```

This should allow MTM to start and probably more

**Comment by sumeetchhetri** [comment]
You're awesome, apologies for not reading the document carefully enough, this explains why it did not work for me in the VM setup as well. Thanks @ChristopherEdwards.

**Comment by sumeetchhetri** [comment]
I tried pulling the latest master and it stopped working again,

docker build --build-arg flags="-b -d -f -i osehra -q -s -u -y" -t osehra .
docker run -p 8001:8001 -p 2223:22 -p 61012:61012 -p 8081:8081 -d -P --sysctl kernel.msgmax=1048700 --sysctl kernel.msgmnb=65536000 --name=osehra osehra

Error Logs
[root@962c03002be2 pip]# tail -f /home/osehra/pip/log/mtm_pip.log
Create server request queue for slot 2
Write Server Type qid(2) to lock file
Allocate memory for clients in server slot 2
Create server request queue for slot 3
Write Server Type qid(3) to lock file
Allocate memory for clients in server slot 3
Create server request queue for slot 4
Write Server Type qid(4) to lock file
Allocate memory for clients in server slot 4
MTM_PIPV02 process started. Process ID = 81

MTM error count: 1
SCA ERROR:      Reason Code: -19
ERROR:  Message: SCAMTM NOTIFICATION:   No active servers.
ERROR:  File: /home/osehra/YDBPIP-master/mtm_V2.4.5/mtmcomm.c Line: 1072
ERROR:  Timestamp: Thu Dec 13 12:05:26 2018


Doing a ./dm
and then
do ^SCAER gives the following error
Message 3036 not found
%YDB-E-SETECODE, Non-empty value assigned to $ECODE (user-defined error trap)
                At M source location vRCgetRecord0Opt+7^RecordDBTBL1D

OSEHRA>

**Comment by ChristopherEdwards** [comment]
Sumeet:

I have a pull request pending review and merge that should fix this. Do note that we should be able to demonstrate using Octo to map FileMan files in Q1 2019 instead of using PIP.

**Comment by sumeetchhetri** [comment]
Thanks a lot @ChristopherEdwards.
