### ISSUE TITLE
Scripts don't work with CentOS8

### ISSUE THREAD

**Issue by ChristopherEdwards** [OSEHRA/docker-vista#53]
Looks like centos:latest was bumped to CentOS8 and the scripts have issues installing yum packages due to different names, etc.

I'm guessing this will be easy to update, but haven't looked closely. It may be worth setting an explicit tag to only build this with CentOS7 (which is what I have to do locally right now as I got CentOS 8 by default).

**Comment by shabiel** [comment]
From our latest testing with Centos8, ssh login with our custom scripts doesn't work. It complains saying for ssh "permission denied".

**Comment by shabiel** [comment]
Implemented by [04dd73a](https://github.com/WorldVistA/docker-vista/commit/04dd73a3b07e8e0445eff6e20d0218f4ce285ca2) (Move to Rocky Linux).
